=== mipel85/MyDevs/phpboost/repository/repository.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT repository (header, app+)>
<!ELEMENT header (#PCDATA)>

<!ELEMENT app (version+)>
<!ATTLIST app
            id CDATA #REQUIRED
            type (kernel|module|template) "module">

<!ELEMENT version (compatibility, download, update?, authors?, description, whatsnew?, warning?)>
<!ATTLIST version
            num CDATA #REQUIRED
            language CDATA #REQUIRED
            localized_language CDATA #IMPLIED
            name CDATA #IMPLIED
            priority (low|medium|high) "medium"
            security-update (true|false) "false"
            pubdate CDATA #REQUIRED>
            
<!ELEMENT compatibility EMPTY>
<!ATTLIST compatibility
            min CDATA #REQUIRED
            max CDATA #IMPLIED>

<!ELEMENT download (#PCDATA)>
<!ATTLIST download url CDATA #REQUIRED>

<!ELEMENT update (#PCDATA)>
<!ATTLIST update url CDATA #REQUIRED>

<!ELEMENT autoupdate (#PCDATA)>
<!ATTLIST autoupdate url CDATA #REQUIRED>

<!ELEMENT authors (author+)>
<!ELEMENT author EMPTY>
<!ATTLIST author
            name CDATA #REQUIRED
            email CDATA #IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT whatsnew (new+)>
<!ELEMENT new (#PCDATA)>
<!ATTLIST new type (feature|improvement|bug|security) "feature">

<!ELEMENT warning (#PCDATA)>
<!ATTLIST warning level (low|medium|high) "low">

=== mipel85/MyDevs/repository/main.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE repository SYSTEM "https://www.phpboost.com/repository/repository.dtd">
<repository>
	<header />
		<app id="kernel" type="kernel">
			<version num="5.2.2" language="french" localized_language="Francais" name="Noyau" pubdate="2019/03/29">
				<compatibility min="5.2" />
				<download url="https://www.phpboost.com/download/">PHPBoost 5.2.2</download>
				<update url="https://www.phpboost.com/download/70-mises-a-jour-phpboost-5-2/">Mise à jour</update>
				<autoupdate url="https://dl.phpboost.com/5.2/diff/diff-phpboost-5.2.1-to-phpboost-5.2.2-optimized.zip">Mise à jour automatique</autoupdate>
				<authors>
					<author name="Equipe PHPBoost" email="contact@phpboost.com" />
				</authors>
				<description>
					La version PHPBoost 5.2.2 améliorera la stabilité de votre site et vous fera profiter des améliorations et corrections suivantes :
				</description>
				<whatsnew>
					<new type="improvement">Suppression du lien de partage Google+ en vue de la fermeture du service le 02/04/19</new>
					<new type="improvement">Mise à jour de la librairie d'icônes Font Awesome en version 5.8.1 pour prendre en compte leurs dernières évolutions</new>
					<new type="improvement">Possibilité d'installer plusieurs versions mineures d'un coup pour rattraper un retard pour ceux qui ont la librairie Curl sur leur serveur (à partir de cette version).</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1714-themeswitcher"&gt;#1714&lt;/a&gt;&lt;/s&gt; ThemeSwitcher</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1873-archive-de-newsletter"&gt;#1873&lt;/a&gt;&lt;/s&gt; archive de newsletter</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1902-lien-sms-modules"&gt;#1902&lt;/a&gt;&lt;/s&gt; Lien SMS modules</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1905-erreur-archivees"&gt;#1905&lt;/a&gt;&lt;/s&gt; Erreur archivées</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1906-modules-liens-web-et-telechargements-pas-de-confirmation-avant-de-signaler-un-lien-mort"&gt;#1906&lt;/a&gt;&lt;/s&gt; Modules Liens Web et Téléchargements : pas de confirmation avant de signaler un lien mort</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1907-invalid-query-lors-de-l-installation-5-2"&gt;#1907&lt;/a&gt;&lt;/s&gt; Invalid Query lors de l'installation 5.2</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1908-statistiques-pages-vues"&gt;#1908&lt;/a&gt;&lt;/s&gt; Statistiques "Pages Vues"</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1909-erreur-lors-de-la-desinstallation-multiple-de-themeslanguesmodules"&gt;#1909&lt;/a&gt;&lt;/s&gt; Erreur lors de la désinstallation multiple de thèmes/langues/modules</new>
				</whatsnew>
			</version>
			<version num="5.2.1" language="french" localized_language="Francais" name="Noyau" priority="high" security-update="true" pubdate="2019/02/15">
				<compatibility min="5.2" />
				<download url="https://www.phpboost.com/download/">PHPBoost 5.2.1</download>
				<update url="https://www.phpboost.com/download/70-mises-a-jour-phpboost-5-2/">Mise à jour</update>
				<autoupdate url="https://dl.phpboost.com/5.2/diff/diff-phpboost-5.2.0-to-phpboost-5.2.1-optimized.zip">Mise à jour automatique</autoupdate>
				<authors>
					<author name="Equipe PHPBoost" email="contact@phpboost.com" />
				</authors>
				<description>
					Plus performante, plus sécurisée, la version PHPBoost 5.2.1 améliorera nettement le référencement de votre site et vous fera profiter de nombreuses améliorations et nouveautés.
				</description>
				<whatsnew>
					<new type="new">Possibilité d'installer les mises à jour mineures directement pour ceux qui disposent de la librairie Curl (fonctionnel à partir de la prochaine mise à jour)</new>
					<new type="improvement">Amélioration de l'affichage des pages de mise à jour du site</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1884-accessibilite-aux-reseaux-sociaux-avec-une-revue-d-ecran"&gt;#1884&lt;/a&gt;&lt;/s&gt; Accessibilité aux réseaux sociaux avec une revue d'écran</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1885-accessibilite-au-module-statistiques-avec-une-revue-d-ecran"&gt;#1885&lt;/a&gt;&lt;/s&gt; Accessibilité au module Statistiques avec une revue d'écran</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1887-probleme-d-accessibilite-au-formulaire-de-configuration-d-envoi-de-mail"&gt;#1887&lt;/a&gt;&lt;/s&gt; Problème d'accessibilité au formulaire de configuration d'envoi de mail</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1888-la-case-qui-permet-d-autoriser-ou-non-l-affichage-sur-un-mobile-n-est-plus-accessible-aux-revues-d-ecran"&gt;#1888&lt;/a&gt;&lt;/s&gt; La case qui permet d'autoriser ou non l'affichage sur un mobile n'est plus accessible aux revues d'écran</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1889-affichage-des-smileys-dans-la-shoutbox"&gt;#1889&lt;/a&gt;&lt;/s&gt; Affichage des smileys dans la shoutbox</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1891-impossible-de-mettre-a-jour-5-1-vers-5-2"&gt;#1891&lt;/a&gt;&lt;/s&gt; Impossible de mettre à jour 5.1 vers 5.2</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1892-message-a-la-fin-de-l-installation"&gt;#1892&lt;/a&gt;&lt;/s&gt; Message d'erreur à la fin de l'installation</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1893-ecriture-de-formule-mathematique-impossible"&gt;#1893&lt;/a&gt;&lt;/s&gt; Ecriture de formule mathématique impossible</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1894-plus-possible-de-choisir-toutes-les-tables-avec-une-revue-d-ecran-au-moment-de-la-sauvegarde-de-la-bdd"&gt;#1894&lt;/a&gt;&lt;/s&gt; Plus possible de choisir toutes les tables avec une revue d'écran au moment de la sauvegarde de la BDD</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1895-fatal-error-lors-du-premier-acces-au-site"&gt;#1895&lt;/a&gt;&lt;/s&gt; Fatal error lors du premier accès au site</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1896-wiki-erreur-404-si-underscore-utilise-dans-nom-categorie"&gt;#1896&lt;/a&gt;&lt;/s&gt; Wiki - erreur 404 si underscore utilisé dans nom catégorie</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1897-le-module-recherches-ne-fonctionne-pas"&gt;#1897&lt;/a&gt;&lt;/s&gt; Le module Recherche ne fonctionne pas</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1898-plus-d-acces-aux-notes-et-a-une-partie-de-l-insertion-des-fichiers"&gt;#1898&lt;/a&gt;&lt;/s&gt; Plus d'accès aux notes et à une partie de l'insertion des fichiers</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1899-echelle-de-notation"&gt;#1899&lt;/a&gt;&lt;/s&gt; Echelle de notation</new>
					<new type="bug">&lt;s&gt;&lt;a href="https://www.phpboost.com/bugtracker/detail/1900-notation-non-visible"&gt;#1900&lt;/a&gt;&lt;/s&gt; Notation non visible</new>
					<new type="security">Mise à jour de la librairie PHPMailer. Correction d'une vulnérabilité potentielle d'injection d'objets. &lt;a href="https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-19296"&gt;CVE-2018-19296&lt;/a&gt;</new>
				</whatsnew>
				<warning level="high">Cette mise à jour contient des correctifs pour améliorer la sécurité du site.</warning>
			</version>
			<version num="5.2.0" language="french" localized_language="Francais" name="Noyau" priority="high" security-update="false" pubdate="2019/01/28">
				<compatibility min="5.1" />
				<download url="https://www.phpboost.com/download/">PHPBoost 5.2.0</download>
				<authors>
					<author name="Julien Briswalter" email="j1.seth@phpboost.com" />
				</authors>
				<description>
					Plus performante, plus sécurisée, PHPBoost 5.2 améliorera nettement le référencement de votre site et vous fera profiter de nombreuses améliorations et nouveautés.
					Pour plus d'informations : &lt;a href="https://www.phpboost.com/news/17-phpboost-5-2/242-phpboost-5-2-est-disponible-en-version-finale/"&gt;PHPBoost 5.2 est disponible en version finale&lt;/a&gt;
				</description>
				<whatsnew>
					<new type="feature">Mise en place d'un module Reseaux Sociaux pour permettre le partage des news, articles etc. directement</new>
					<new type="feature">Possibilite de mettre en place l'authentification avec son compte Facebook, Google+, LinkedIn ou Twitter</new>
					<new type="feature">Integration de la librairie d'icones FontAwesome 5</new>
					<new type="improvment">Amelioration du SEO des differentes pages du site, pour faciliter le referencement</new>
					<new type="improvment">Installation/suppression de plusieurs themes, langues, modules en meme temps grace a une interface d'administration plus moderne</new>
					<new type="improvment">Mise a jour du framework javascript jQuery</new>
					<new type="improvment">Adaptation du code pour le rendre compatible avec php 7.2 et 7.3</new>
					<new type="improvment">Mise en place d'un nouveau theme "Base" epure et amelioration de l'accessibilite</new>
					<new type="improvment">Mise a jour du captcha ReCaptcha de Google avec la possibilite de mettre en place invisible ReCaptcha</new>
					<new type="improvment">Optimisation du kernel et du theme pour un affichage plus rapide</new>
